### ISSUE TITLE
Enemies like to "jiggle" back and forth.

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#472]
So the overworld enemies seem to be more likely to "shake" or "jiggle" back and forth instead of coming towards you, it only happens sometimes and they do snap out of it after a while. I believe there is something in the enemy AI, but I have not yet tried to look for the reason as it is late where I live.

**Comment by Tricky1975** [comment]
Yeah, this is a known issue.
The "evil" lies in that the enemies have a "perfect" finder of your location in the AI that controls them, making it impossible to escape them. That's why I made them go back to their original position if they get out of that position by a certain distance. The exact distance depends on the chosen difficulty setting and on how high the enemy is in level compared to yours. The pythagorean theorism is used to determine this distance. Once this distance appears reached the AI gets a bit out of control. I have not yet found out what causes it, but I'm on the job ;)

(Was also noted in #360, although it was there noted so technically I can understand peeps had trouble understanding that) :)

**Comment by Tricky1975** [comment]
I shall close this one. Like I said before this one was already noted in #360, and it works a bit confusing to see the same bug twice in my list ;)
