### ISSUE TITLE
Transport pads allow infinite items.

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#473]
While exploring the planet where wendicka discovers how to use transport pads to heal and save I noticed that saving resets the items around the transport pad and allows the player to collect infinite amounts of them.

**Comment by Tricky1975** [comment]
That was intentional ;)
I chose this way to make the game more item based. It just depends on how far you wish to "grind"
You should also notice that the item bags have their limits. In the hard mode your bags are full very quickly (due to the low limits that mode has),and then you must really be selective. Btw, the enemies and even the non-scenario bosses respawn too, so it's not only advantages I'm giving ya ;)
