### ISSUE TITLE
Un-able to continue story after thief bossfight

### ISSUE THREAD

**Issue by ghost** [Tricky1975/Star-Story#485]
This should be the warp location but it does nothing.
![nayttokuva 2016-07-07 kello 17 24 32](https://cloud.githubusercontent.com/assets/20288180/16656564/d7ef9ffa-4467-11e6-87be-0cfb0e33123d.png)

**Comment by Tricky1975** [comment]
The barrier did not disappear I see...
The North tree should have disappeared (the tree Wendicka touches).
I shall try if I can get you past this in chat.

**Comment by Tricky1975** [comment]
I deem it possible this bug lurks on every dungeon with a boss that can be attacked multiple times. Since I could not replicate this so far I call on all players reading this (alpha beta or even stable) to let me know if something similar happens to you and provide me all data you think I may need.

**Comment by Tricky1975** [comment]
I suddenly got an idea of what happened here, fill me in if this is true or not.
As an alpha tester you got access to the "save where you want" cheat. Did you save the game AFTER killing the boss and did you shutdown the game after that, loading the savegame later.

If you do that, the "boss-barrier" will always respawn, but the boss will remain out. This is a bit of an issue that I cannot fix, and since the normal players cannot encounter this "bug" (since this cheat will not be accessible by them), this will not be something I can "fix". (It is also for this reason the "emergency save" feature is disabled once you defeat a boss, until you leave the dungeon, or reset it with a transporter pad).

**Comment by ghost** [comment]
Remember how I said "I'll walk back to the boss to see if it happens again"? That's because I had a completely normal save at that point of the game.

**Comment by Tricky1975** [comment]
Hmmm, yeah... This still remains odd then....

**Comment by Tricky1975** [comment]
Entering the hut here the save computer is located should now respawn all enemies including the boss, and that should fix this bug.
If it happens again please tell me in this very issue (even though it's closed you can still reply to it) and I shall re-open it.
