### ISSUE TITLE
Add "What is this?" or similiar button to start screen

### ISSUE THREAD

**Issue by honno** [Tricky1975/Star-Story#545]
As discussed with Phant, the systems for logging into GJAPI and the Anna system aren't well explained. A hoverable/clickable button that explains in some detail would benefit the users initial experience of the game.

**Comment by Tricky1975** [comment]
[This draft](http://starstory.sourceforge.net/uTBBS/index.php?A=Read&C=Doc&Doc=Netwerk) is a full explanation of the GJAPI and the bot named Anna. I shall later today see how to put this best in the game itself by means of a "What's this?" button. Linking to that on-line page might not be such a bad idea, since a lot of professional software does the same these days.

**Comment by Tricky1975** [comment]
All done 😉
